spring:
  profiles: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_stackoverflow?useSSL=false&allowPublicKeyRetrieval=true&useLegacyAuth=false
#    username: user_stackoverflow
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

